# Adapted from https://github.com/commercialhaskell/stack
language: nix
sudo: false

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work

matrix:
  fast_finish: true
  include:
    # Add build targets here
    - env: GHCVER=8.4.4 CACHE_NAME=8.2.1 BUILD_BINARY=1
      compiler: ": #stack 8.4.4"
      addons: {apt: {packages: [ghc-8.4.4], sources: [hvr-ghc]}}

install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ./.travis/install-stack.sh
 - sudo apt-get install build-essential m4 openjdk-8-jdk libgmp-dev libmpfr-dev pkg-config flex z3 libz3-dev maven opam python3


script:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - |
   set -ex
   # Run tests
   stack build --haddock --no-haddock-deps --coverage --bench --no-run-benchmarks --test --no-run-tests --pedantic
   set +ex
 - |
   cd /home/appveyor/projects/kore/src/main/k/working
   make test-k

after_success:
